# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AppliCantStop.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(817, 706)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(817, 706))
        MainWindow.setMaximumSize(QtCore.QSize(817, 706))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/interface/De5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Plateau = QtWidgets.QLabel(self.centralwidget)
        self.Plateau.setEnabled(True)
        self.Plateau.setGeometry(QtCore.QRect(0, 0, 821, 661))
        self.Plateau.setText("")
        self.Plateau.setPixmap(QtGui.QPixmap(":/interface/montagne-sigmar.jpg"))
        self.Plateau.setObjectName("Plateau")
        self.DeA = QtWidgets.QLabel(self.centralwidget)
        self.DeA.setGeometry(QtCore.QRect(50, 50, 40, 40))
        self.DeA.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DeA.setText("")
        self.DeA.setPixmap(QtGui.QPixmap(":/interface/De.png"))
        self.DeA.setScaledContents(True)
        self.DeA.setObjectName("DeA")
        self.DeB = QtWidgets.QLabel(self.centralwidget)
        self.DeB.setGeometry(QtCore.QRect(50, 110, 40, 40))
        self.DeB.setText("")
        self.DeB.setPixmap(QtGui.QPixmap(":/interface/De.png"))
        self.DeB.setScaledContents(True)
        self.DeB.setObjectName("DeB")
        self.DeC = QtWidgets.QLabel(self.centralwidget)
        self.DeC.setGeometry(QtCore.QRect(110, 50, 40, 40))
        self.DeC.setText("")
        self.DeC.setPixmap(QtGui.QPixmap(":/interface/De.png"))
        self.DeC.setScaledContents(True)
        self.DeC.setObjectName("DeC")
        self.DeD = QtWidgets.QLabel(self.centralwidget)
        self.DeD.setGeometry(QtCore.QRect(110, 110, 40, 40))
        self.DeD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DeD.setText("")
        self.DeD.setPixmap(QtGui.QPixmap(":/interface/De.png"))
        self.DeD.setScaledContents(True)
        self.DeD.setObjectName("DeD")
        self.Continue = QtWidgets.QPushButton(self.centralwidget)
        self.Continue.setGeometry(QtCore.QRect(650, 40, 101, 51))
        self.Continue.setObjectName("Continue")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(650, 240, 101, 51))
        self.Stop.setObjectName("Stop")
        self.Choix_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.Choix_1.setGeometry(QtCore.QRect(650, 120, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Choix_1.setFont(font)
        self.Choix_1.setObjectName("Choix_1")
        self.Choix_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.Choix_2.setGeometry(QtCore.QRect(650, 160, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Choix_2.setFont(font)
        self.Choix_2.setObjectName("Choix_2")
        self.Choix_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.Choix_3.setGeometry(QtCore.QRect(650, 200, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Choix_3.setFont(font)
        self.Choix_3.setObjectName("Choix_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(190, 50, 120, 80))
        self.groupBox.setObjectName("groupBox")
        self.JoueurCourant = QtWidgets.QLabel(self.groupBox)
        self.JoueurCourant.setGeometry(QtCore.QRect(40, 30, 41, 41))
        self.JoueurCourant.setText("")
        self.JoueurCourant.setPixmap(QtGui.QPixmap(":/interface/PionBlanc.png"))
        self.JoueurCourant.setScaledContents(True)
        self.JoueurCourant.setObjectName("JoueurCourant")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 21))
        self.menubar.setObjectName("menubar")
        self.menuPartie = QtWidgets.QMenu(self.menubar)
        self.menuPartie.setObjectName("menuPartie")
        self.menuNouvelle_partie = QtWidgets.QMenu(self.menuPartie)
        self.menuNouvelle_partie.setObjectName("menuNouvelle_partie")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setSizeIncrement(QtCore.QSize(0, 0))
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionSauvegarder = QtWidgets.QAction(MainWindow)
        self.actionSauvegarder.setObjectName("actionSauvegarder")
        self.actionCharger = QtWidgets.QAction(MainWindow)
        self.actionCharger.setObjectName("actionCharger")
        self.actionRegles = QtWidgets.QAction(MainWindow)
        self.actionRegles.setObjectName("actionRegles")
        self.actionA_propos = QtWidgets.QAction(MainWindow)
        self.actionA_propos.setObjectName("actionA_propos")
        self.action2_joueurs = QtWidgets.QAction(MainWindow)
        self.action2_joueurs.setObjectName("action2_joueurs")
        self.action3_joueurs = QtWidgets.QAction(MainWindow)
        self.action3_joueurs.setObjectName("action3_joueurs")
        self.action4_joueurs = QtWidgets.QAction(MainWindow)
        self.action4_joueurs.setObjectName("action4_joueurs")
        self.menuNouvelle_partie.addSeparator()
        self.menuNouvelle_partie.addAction(self.action2_joueurs)
        self.menuNouvelle_partie.addAction(self.action3_joueurs)
        self.menuNouvelle_partie.addAction(self.action4_joueurs)
        self.menuPartie.addAction(self.menuNouvelle_partie.menuAction())
        self.menuPartie.addAction(self.actionSauvegarder)
        self.menuPartie.addAction(self.actionCharger)
        self.menuPartie.addSeparator()
        self.menuPartie.addAction(self.actionQuitter)
        self.menuAide.addAction(self.actionRegles)
        self.menuAide.addAction(self.actionA_propos)
        self.menubar.addAction(self.menuPartie.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Can\'t Stop"))
        self.Continue.setText(_translate("MainWindow", "Continue ..."))
        self.Stop.setText(_translate("MainWindow", "STOP !!!"))
        self.Choix_1.setText(_translate("MainWindow", "Choix 1"))
        self.Choix_2.setText(_translate("MainWindow", "Choix 2"))
        self.Choix_3.setText(_translate("MainWindow", "Choix 3"))
        self.groupBox.setTitle(_translate("MainWindow", "Tour du joueur"))
        self.menuPartie.setTitle(_translate("MainWindow", "Partie"))
        self.menuNouvelle_partie.setTitle(_translate("MainWindow", "Nouvelle partie"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))
        self.actionSauvegarder.setText(_translate("MainWindow", "Sauvegarder"))
        self.actionSauvegarder.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCharger.setText(_translate("MainWindow", "Charger"))
        self.actionCharger.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionRegles.setText(_translate("MainWindow", "Règles"))
        self.actionA_propos.setText(_translate("MainWindow", "A propos..."))
        self.action2_joueurs.setText(_translate("MainWindow", "2 joueurs"))
        self.action2_joueurs.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action3_joueurs.setText(_translate("MainWindow", "3 joueurs"))
        self.action3_joueurs.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.action4_joueurs.setText(_translate("MainWindow", "4 joueurs"))
        self.action4_joueurs.setShortcut(_translate("MainWindow", "Ctrl+4"))
import images_rc
