# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NouvellePartie.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NouvellePartie(object):
    def setupUi(self, NouvellePartie):
        NouvellePartie.setObjectName("NouvellePartie")
        NouvellePartie.resize(412, 287)
        NouvellePartie.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(NouvellePartie)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.NbJoueurs = QtWidgets.QComboBox(NouvellePartie)
        self.NbJoueurs.setGeometry(QtCore.QRect(160, 20, 69, 22))
        self.NbJoueurs.setObjectName("NbJoueurs")
        self.NbJoueurs.addItem("")
        self.NbJoueurs.addItem("")
        self.NbJoueurs.addItem("")
        self.label = QtWidgets.QLabel(NouvellePartie)
        self.label.setGeometry(QtCore.QRect(40, 20, 101, 20))
        self.label.setObjectName("label")
        self._1_Humain = QtWidgets.QRadioButton(NouvellePartie)
        self._1_Humain.setGeometry(QtCore.QRect(100, 70, 61, 17))
        self._1_Humain.setObjectName("_1_Humain")
        self._1_buttonGroup = QtWidgets.QButtonGroup(NouvellePartie)
        self._1_buttonGroup.setObjectName("_1_buttonGroup")
        self._1_buttonGroup.addButton(self._1_Humain)
        self._1_Bot = QtWidgets.QRadioButton(NouvellePartie)
        self._1_Bot.setGeometry(QtCore.QRect(170, 70, 61, 17))
        self._1_Bot.setObjectName("_1_Bot")
        self._1_buttonGroup.addButton(self._1_Bot)
        self._1_Risque = QtWidgets.QSlider(NouvellePartie)
        self._1_Risque.setGeometry(QtCore.QRect(230, 70, 160, 22))
        self._1_Risque.setSliderPosition(50)
        self._1_Risque.setOrientation(QtCore.Qt.Horizontal)
        self._1_Risque.setInvertedAppearance(False)
        self._1_Risque.setObjectName("_1_Risque")
        self._1_Couleur = QtWidgets.QComboBox(NouvellePartie)
        self._1_Couleur.setGeometry(QtCore.QRect(20, 70, 69, 22))
        self._1_Couleur.setObjectName("_1_Couleur")
        self._1_Couleur.addItem("")
        self._1_Couleur.addItem("")
        self._1_Couleur.addItem("")
        self._1_Couleur.addItem("")
        self._1_Couleur.addItem("")
        self._1_Couleur.addItem("")
        self._1_Couleur.addItem("")
        self._1_Couleur.addItem("")
        self._2_Risque = QtWidgets.QSlider(NouvellePartie)
        self._2_Risque.setGeometry(QtCore.QRect(230, 110, 160, 22))
        self._2_Risque.setSliderPosition(50)
        self._2_Risque.setOrientation(QtCore.Qt.Horizontal)
        self._2_Risque.setInvertedAppearance(False)
        self._2_Risque.setObjectName("_2_Risque")
        self._2_Bot = QtWidgets.QRadioButton(NouvellePartie)
        self._2_Bot.setGeometry(QtCore.QRect(170, 110, 61, 17))
        self._2_Bot.setObjectName("_2_Bot")
        self._2_buttonGroup = QtWidgets.QButtonGroup(NouvellePartie)
        self._2_buttonGroup.setObjectName("_2_buttonGroup")
        self._2_buttonGroup.addButton(self._2_Bot)
        self._2_Humain = QtWidgets.QRadioButton(NouvellePartie)
        self._2_Humain.setGeometry(QtCore.QRect(100, 110, 61, 17))
        self._2_Humain.setObjectName("_2_Humain")
        self._2_buttonGroup.addButton(self._2_Humain)
        self._2_Couleur = QtWidgets.QComboBox(NouvellePartie)
        self._2_Couleur.setGeometry(QtCore.QRect(20, 110, 69, 22))
        self._2_Couleur.setObjectName("_2_Couleur")
        self._2_Couleur.addItem("")
        self._2_Couleur.addItem("")
        self._2_Couleur.addItem("")
        self._2_Couleur.addItem("")
        self._2_Couleur.addItem("")
        self._2_Couleur.addItem("")
        self._2_Couleur.addItem("")
        self._2_Couleur.addItem("")
        self._3_Risque = QtWidgets.QSlider(NouvellePartie)
        self._3_Risque.setGeometry(QtCore.QRect(230, 150, 160, 22))
        self._3_Risque.setSliderPosition(50)
        self._3_Risque.setOrientation(QtCore.Qt.Horizontal)
        self._3_Risque.setInvertedAppearance(False)
        self._3_Risque.setObjectName("_3_Risque")
        self._3_Bot = QtWidgets.QRadioButton(NouvellePartie)
        self._3_Bot.setGeometry(QtCore.QRect(170, 150, 61, 17))
        self._3_Bot.setObjectName("_3_Bot")
        self._3_buttonGroup = QtWidgets.QButtonGroup(NouvellePartie)
        self._3_buttonGroup.setObjectName("_3_buttonGroup")
        self._3_buttonGroup.addButton(self._3_Bot)
        self._3_Couleur = QtWidgets.QComboBox(NouvellePartie)
        self._3_Couleur.setGeometry(QtCore.QRect(20, 150, 69, 22))
        self._3_Couleur.setObjectName("_3_Couleur")
        self._3_Couleur.addItem("")
        self._3_Couleur.addItem("")
        self._3_Couleur.addItem("")
        self._3_Couleur.addItem("")
        self._3_Couleur.addItem("")
        self._3_Couleur.addItem("")
        self._3_Couleur.addItem("")
        self._3_Couleur.addItem("")
        self._3_Humain = QtWidgets.QRadioButton(NouvellePartie)
        self._3_Humain.setGeometry(QtCore.QRect(100, 150, 61, 17))
        self._3_Humain.setObjectName("_3_Humain")
        self._3_buttonGroup.addButton(self._3_Humain)
        self._4_Humain = QtWidgets.QRadioButton(NouvellePartie)
        self._4_Humain.setGeometry(QtCore.QRect(100, 190, 61, 17))
        self._4_Humain.setObjectName("_4_Humain")
        self._4_buttonGroup = QtWidgets.QButtonGroup(NouvellePartie)
        self._4_buttonGroup.setObjectName("_4_buttonGroup")
        self._4_buttonGroup.addButton(self._4_Humain)
        self._4_Couleur = QtWidgets.QComboBox(NouvellePartie)
        self._4_Couleur.setGeometry(QtCore.QRect(20, 190, 69, 22))
        self._4_Couleur.setObjectName("_4_Couleur")
        self._4_Couleur.addItem("")
        self._4_Couleur.addItem("")
        self._4_Couleur.addItem("")
        self._4_Couleur.addItem("")
        self._4_Couleur.addItem("")
        self._4_Couleur.addItem("")
        self._4_Couleur.addItem("")
        self._4_Couleur.addItem("")
        self._4_Bot = QtWidgets.QRadioButton(NouvellePartie)
        self._4_Bot.setGeometry(QtCore.QRect(170, 190, 61, 17))
        self._4_Bot.setObjectName("_4_Bot")
        self._4_buttonGroup.addButton(self._4_Bot)
        self._4_Risque = QtWidgets.QSlider(NouvellePartie)
        self._4_Risque.setGeometry(QtCore.QRect(230, 190, 160, 22))
        self._4_Risque.setSliderPosition(50)
        self._4_Risque.setOrientation(QtCore.Qt.Horizontal)
        self._4_Risque.setInvertedAppearance(False)
        self._4_Risque.setObjectName("_4_Risque")
        self.label_2 = QtWidgets.QLabel(NouvellePartie)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 91, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(NouvellePartie)
        self.buttonBox.accepted.connect(NouvellePartie.accept)
        self.buttonBox.rejected.connect(NouvellePartie.reject)
        QtCore.QMetaObject.connectSlotsByName(NouvellePartie)

    def retranslateUi(self, NouvellePartie):
        _translate = QtCore.QCoreApplication.translate
        NouvellePartie.setWindowTitle(_translate("NouvellePartie", "Nouvelle partie"))
        self.NbJoueurs.setCurrentText(_translate("NouvellePartie", "2"))
        self.NbJoueurs.setItemText(0, _translate("NouvellePartie", "2"))
        self.NbJoueurs.setItemText(1, _translate("NouvellePartie", "3"))
        self.NbJoueurs.setItemText(2, _translate("NouvellePartie", "4"))
        self.label.setText(_translate("NouvellePartie", "Nombre de joueurs"))
        self._1_Humain.setText(_translate("NouvellePartie", "Humain"))
        self._1_Bot.setText(_translate("NouvellePartie", "Bot"))
        self._1_Couleur.setItemText(0, _translate("NouvellePartie", "Blanc"))
        self._1_Couleur.setItemText(1, _translate("NouvellePartie", "Orange"))
        self._1_Couleur.setItemText(2, _translate("NouvellePartie", "Jaune"))
        self._1_Couleur.setItemText(3, _translate("NouvellePartie", "Rouge"))
        self._1_Couleur.setItemText(4, _translate("NouvellePartie", "Bleu"))
        self._1_Couleur.setItemText(5, _translate("NouvellePartie", "Violet"))
        self._1_Couleur.setItemText(6, _translate("NouvellePartie", "Gris"))
        self._1_Couleur.setItemText(7, _translate("NouvellePartie", "Vert"))
        self._2_Bot.setText(_translate("NouvellePartie", "Bot"))
        self._2_Humain.setText(_translate("NouvellePartie", "Humain"))
        self._2_Couleur.setItemText(0, _translate("NouvellePartie", "Blanc"))
        self._2_Couleur.setItemText(1, _translate("NouvellePartie", "Orange"))
        self._2_Couleur.setItemText(2, _translate("NouvellePartie", "Jaune"))
        self._2_Couleur.setItemText(3, _translate("NouvellePartie", "Rouge"))
        self._2_Couleur.setItemText(4, _translate("NouvellePartie", "Bleu"))
        self._2_Couleur.setItemText(5, _translate("NouvellePartie", "Violet"))
        self._2_Couleur.setItemText(6, _translate("NouvellePartie", "Gris"))
        self._2_Couleur.setItemText(7, _translate("NouvellePartie", "Vert"))
        self._3_Bot.setText(_translate("NouvellePartie", "Bot"))
        self._3_Couleur.setItemText(0, _translate("NouvellePartie", "Blanc"))
        self._3_Couleur.setItemText(1, _translate("NouvellePartie", "Orange"))
        self._3_Couleur.setItemText(2, _translate("NouvellePartie", "Jaune"))
        self._3_Couleur.setItemText(3, _translate("NouvellePartie", "Rouge"))
        self._3_Couleur.setItemText(4, _translate("NouvellePartie", "Bleu"))
        self._3_Couleur.setItemText(5, _translate("NouvellePartie", "Violet"))
        self._3_Couleur.setItemText(6, _translate("NouvellePartie", "Gris"))
        self._3_Couleur.setItemText(7, _translate("NouvellePartie", "Vert"))
        self._3_Humain.setText(_translate("NouvellePartie", "Humain"))
        self._4_Humain.setText(_translate("NouvellePartie", "Humain"))
        self._4_Couleur.setItemText(0, _translate("NouvellePartie", "Blanc"))
        self._4_Couleur.setItemText(1, _translate("NouvellePartie", "Orange"))
        self._4_Couleur.setItemText(2, _translate("NouvellePartie", "Jaune"))
        self._4_Couleur.setItemText(3, _translate("NouvellePartie", "Rouge"))
        self._4_Couleur.setItemText(4, _translate("NouvellePartie", "Bleu"))
        self._4_Couleur.setItemText(5, _translate("NouvellePartie", "Violet"))
        self._4_Couleur.setItemText(6, _translate("NouvellePartie", "Gris"))
        self._4_Couleur.setItemText(7, _translate("NouvellePartie", "Vert"))
        self._4_Bot.setText(_translate("NouvellePartie", "Bot"))
        self.label_2.setText(_translate("NouvellePartie", "Prise de risque"))
